import {
    AuditOutlined,
    BarcodeOutlined,
    CheckOutlined,
    ClusterOutlined,
    CodeOutlined,
    CreditCardOutlined,
    DashboardOutlined,
    DeleteOutlined,
    DownOutlined,
    EditOutlined,
    FieldTimeOutlined,
    GlobalOutlined,
    GoldOutlined,
    HddOutlined,
    HistoryOutlined,
    LeftOutlined,
    LoadingOutlined,
    LockOutlined,
    MedicineBoxOutlined,
    MoneyCollectOutlined,
    PartitionOutlined,
    PlusOutlined,
    ProfileOutlined,
    SaveOutlined,
    SearchOutlined,
    SettingOutlined,
    ShopOutlined,
    SmileOutlined,
    TransactionOutlined,
    UndoOutlined,
    UserOutlined,
} from '@ant-design/icons';
import * as React from 'react';

interface Icons {
    [key: string]: JSX.Element;
}

export const Icon: Icons = {
    action: <DownOutlined />,
    barcode: <BarcodeOutlined />,
    back: <LeftOutlined />,
    category: <ClusterOutlined />,
    code: <CodeOutlined />,
    dashboard: <DashboardOutlined />,
    delete: <DeleteOutlined />,
    edit: <EditOutlined />,
    global: <GlobalOutlined />,
    hdd: <HddOutlined />,
    history: <HistoryOutlined />,
    list: <ProfileOutlined />,
    loading: <LoadingOutlined />,
    lock: <LockOutlined />,
    medicine_box: <MedicineBoxOutlined />,
    payment: <CreditCardOutlined />,
    pending: <FieldTimeOutlined />,
    plus: <PlusOutlined />,
    return: <UndoOutlined />,
    save: <SaveOutlined />,
    sales: <MoneyCollectOutlined />,
    search: <SearchOutlined />,
    select: <CheckOutlined />,
    setting: <SettingOutlined />,
    shop: <ShopOutlined />,
    smile: <SmileOutlined style={{ color: '#108ee9' }} />,
    supplier: <AuditOutlined />,
    transaction: <TransactionOutlined />,
    uom: <GoldOutlined />,
    user: <UserOutlined />,
    variant: <PartitionOutlined />,
};
